baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = "Leye's amazing website"

paginate = 4

[params]
    dateFormat = "Jan 2, 2006"
    description = "Leye's amazing website" 

[taxonomies]
    author = "users"
    category = "categories"